name: ConnectNotify
version: ${version}
main: com.minekube.connect.notify.bukkit.BukkitConnectNotify
api-version: '1.13'
folia-supported: true
description: ${description}
author: Minekube
website: https://connect.minekube.com
softdepend:
  - connect
  - Connect

